apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: test-rag-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  test-rag-1
    app.kubernetes.io/part-of: test-rag-1  
  name: test-rag-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  test-rag-1 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  test-rag-1
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: test-rag-1-model-config
        - configMapRef:
            name: test-rag-1-database-config
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
